name: Close Non-Bug Issues

on:
  issues:
    types: [opened]

jobs:
  close-issue-if-not-bug:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the issue contains "bug"
        id: check_bug
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"

          if [[ "$ISSUE_TITLE" =~ [Bb]ug ]] || [[ "$ISSUE_BODY" =~ [Bb]ug ]]; then
            echo "This is a bug-related issue. Keeping it open."
            echo "is_bug=true" >> $GITHUB_ENV
          else
            echo "This is not a bug-related issue. Closing it."
            echo "is_bug=false" >> $GITHUB_ENV
          fi

      - name: Close issue and add comment if not bug
        if: env.is_bug == 'false'
        run: |
          COMMENT="If this is a feature request, unfortunately no new features are planned at present. The idea behind this project is to keep the feature set as minimal as possible. Consider forking this and creating your own image to suit your requirements. Check previous issues for a solution. If this is an issue please check previous issues as it is likely already covered. If it's not covered you are going to have to make a clone of this repo and run it locally to see what your specific issue is. Note: If you feel like you have found a genuine bug that affects the usage please raise an issue with the logs and specific bug report (also nice if you can investigate it). Thanks and best of luck!"

          gh issue close ${{ github.event.issue.number }} --comment "$COMMENT" --repo ${{ github.repository }}
